dbtlearn:
  outputs:
    dev:
      account: "{{ env_var('ACCOUNT_NAME') }}"
      database: "{{ env_var('DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PWD') }}"
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
  target: "{{ env_var('TARGET') }}"