name: Deployment to Dev
on:
  push:
    branches:
      - features/*
jobs:
  lint:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install SQLFluff       
        run: pip install sqlfluff
      - name: Lint Code
        run: sqlfluff  lint ./dbtlearn/models --dialect=snowflake
  dbt_test:         
    runs-on: ubuntu-latest
    environment: dev
    env:
      ACCOUNT_NAME: ${{ vars.ACCOUNT_NAME }}
      DATABASE: ${{ vars.DATABASE }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}      
      SNOWFLAKE_PWD: ${{ secrets.SNOWFLAKE_PWD }}      
      TARGET: ${{ vars.TARGET }}      
    steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Setup Python environment
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"            
        - name: Install dbt
          run: pip install dbt-snowflake   
        - name: Run DBT Version
          run : dbt --version
        - name: Echo My password
          run: echo "$SNOWFLAKE_PWD"  
        - name: Check Connection
          run : dbt debug --project-dir=./dbtlearn   --profiles-dir=./dbtlearn